src/main/java/com/brew/oauth20/server/service/TokenService.java
src/main/java/com/brew/oauth20/server/service/impl/TokenServiceImpl.java
src/main/java/com/brew/oauth20/server/utils/StringUtils.java
src/test/java/com/brew/oauth20/server/Controller/GreetingControllerTest.java
src/test/java/com/brew/oauth20/server/Integration/GreetingRequestTest.java
src/test/java/com/brew/oauth20/server/Service/GreetingServiceTest.java
src/test/java/com/brew/oauth20/server/utils/StringUtilsTest.java

fix test folder and package names
add StringUtils
change GenerateRandomTokenString as GenerateSecureRandomString

feat(TMID-39): fix test folder and package names

---

pom.xml

[Automated] Merge release/v1.2.0 into main

---

pom.xml

[Automated] Merge release/v1.2.1 into main

---

pom.xml

[Automated] Merge release/v1.2.2 into main

---

pom.xml

[Automated] Merge release/v1.3.1 into main

---

pom.xml

[Automated] Merge release/v1.3.2 into main

---

pom.xml

[Automated] Merge release/v1.3.3 into main

---

pom.xml

[Automated] Merge release/v1.3.4 into main

---

src/main/java/com/brew/oauth20/server/controller/AuthorizeController.java

[Automated] Merge release/v1.3.7 into main

---

pom.xml

[Automated] Merge release/v1.3.8 into main

---

pom.xml

[Automated] Merge release/v1.4.0 into main

---

pom.xml

[Automated] Merge release/v1.5.0 into main

---

src/main/java/com/brew/oauth20/server/component/UserCookieManager.java
src/main/java/com/brew/oauth20/server/component/impl/UserCookieManagerImpl.java
src/main/java/com/brew/oauth20/server/controller/AuthorizeController.java
src/main/java/com/brew/oauth20/server/data/ClientUser.java
src/main/java/com/brew/oauth20/server/exception/ClientsUserNotFoundException.java
src/main/java/com/brew/oauth20/server/model/UserCookieModel.java
src/main/java/com/brew/oauth20/server/repository/ClientsUserRepository.java
src/main/java/com/brew/oauth20/server/service/ClientUserService.java
src/main/java/com/brew/oauth20/server/service/RefreshTokenService.java
src/main/java/com/brew/oauth20/server/service/TokenService.java
src/main/java/com/brew/oauth20/server/service/impl/ClientUserServiceImpl.java
src/main/java/com/brew/oauth20/server/service/impl/RefreshTokenServiceImpl.java
src/main/java/com/brew/oauth20/server/service/impl/TokenServiceImpl.java
src/test/java/com/brew/oauth20/server/component/UserCookieManagerTest.java
src/test/java/com/brew/oauth20/server/fixture/ClientsUserFixture.java
src/test/java/com/brew/oauth20/server/integration/AuthorizeControllerTest.java
src/test/java/com/brew/oauth20/server/integration/BaseAuthorizeControllerTest.java
src/test/java/com/brew/oauth20/server/model/UserCookieModelTest.java
src/test/java/com/brew/oauth20/server/service/RefreshTokenServiceTest.java
src/test/java/com/brew/oauth20/server/service/TokenServiceTest.java

feat(https://brewww.atlassian.net/jira/software/projects/TMID/boards/84?assignee=712020%3Ad3424183-3eb0-42c9-a7ee-aa2274ec8c27&selectedIssue=TMID-357) : Change user id related fields to String in OAuth Server Project.

feat(TMID-357): changed user id related fields from long to string.

---

pom.xml

[Automated] Merge release/v1.6.0 into main

---

pom.xml

[Automated] Merge release/v1.7.1 into main

---

pom.xml

[Automated] Merge release/v1.7.2 into main

---

pom.xml

[Automated] Merge release/v1.7.4 into main

---

pom.xml

[Automated] Merge release/v1.7.5 into main

---

pom.xml

[Automated] Merge release/v1.7.6 into main

---

pom.xml

[Automated] Merge release/v1.7.7 into main

---

pom.xml

[Automated] Merge release/v1.7.8 into main

---

src/main/java/com/brew/oauth20/server/controller/AuthorizeController.java
src/main/java/com/brew/oauth20/server/data/ClientUserScope.java
src/main/java/com/brew/oauth20/server/repository/ClientsUserRepository.java
src/main/java/com/brew/oauth20/server/service/ClientUserService.java
src/main/java/com/brew/oauth20/server/service/impl/ClientUserServiceImpl.java
src/test/java/com/brew/oauth20/server/fixture/ClientsUserFixture.java
src/test/java/com/brew/oauth20/server/service/ClientUserServiceTest.java

add clientUserScopes left join to ClientsUserRepository.findByClientIdAndUserId query

feat(TMID-883): refactor ClientUserService.getOrCreate

---

pom.xml

[Automated] Merge release/v1.10.0 into main

---

pom.xml

[Automated] Merge release/v1.10.1 into main

---

pom.xml

[Automated] Merge release/v1.10.2 into main

---

pom.xml

[Automated] Merge release/v1.11.0 into main

---

pom.xml

[Automated] Merge release/v1.11.1 into main

---

pom.xml

[Automated] Merge release/v1.11.2 into main

---

pom.xml

[Automated] Merge release/v2.0.1 into main

---

pom.xml

[Automated] Merge release/v2.0.3 into main
